/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.resources.v2.types;

import com.cohere.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ChatContentStartEvent.Builder.class)
public final class ChatContentStartEvent implements IChatStreamEventType {
    private final Optional<Integer> index;

    private final Optional<ChatContentStartEventDelta> delta;

    private final Map<String, Object> additionalProperties;

    private ChatContentStartEvent(
            Optional<Integer> index,
            Optional<ChatContentStartEventDelta> delta,
            Map<String, Object> additionalProperties) {
        this.index = index;
        this.delta = delta;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("index")
    public Optional<Integer> getIndex() {
        return index;
    }

    @JsonProperty("delta")
    public Optional<ChatContentStartEventDelta> getDelta() {
        return delta;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ChatContentStartEvent && equalTo((ChatContentStartEvent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ChatContentStartEvent other) {
        return index.equals(other.index) && delta.equals(other.delta);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.index, this.delta);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> index = Optional.empty();

        private Optional<ChatContentStartEventDelta> delta = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ChatContentStartEvent other) {
            index(other.getIndex());
            delta(other.getDelta());
            return this;
        }

        @JsonSetter(value = "index", nulls = Nulls.SKIP)
        public Builder index(Optional<Integer> index) {
            this.index = index;
            return this;
        }

        public Builder index(Integer index) {
            this.index = Optional.of(index);
            return this;
        }

        @JsonSetter(value = "delta", nulls = Nulls.SKIP)
        public Builder delta(Optional<ChatContentStartEventDelta> delta) {
            this.delta = delta;
            return this;
        }

        public Builder delta(ChatContentStartEventDelta delta) {
            this.delta = Optional.of(delta);
            return this;
        }

        public ChatContentStartEvent build() {
            return new ChatContentStartEvent(index, delta, additionalProperties);
        }
    }
}
