/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.resources.v2.requests;

import com.cohere.api.core.ObjectMappers;
import com.cohere.api.types.ParseDocument;
import com.cohere.api.types.ParseOutputFormat;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ParseRequest.Builder.class)
public final class ParseRequest {
    private final String model;

    private final ParseDocument document;

    private final Optional<ParseOutputFormat> outputFormat;

    private final Map<String, Object> additionalProperties;

    private ParseRequest(
            String model,
            ParseDocument document,
            Optional<ParseOutputFormat> outputFormat,
            Map<String, Object> additionalProperties) {
        this.model = model;
        this.document = document;
        this.outputFormat = outputFormat;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The name of a compatible Cohere parse model.
     */
    @JsonProperty("model")
    public String getModel() {
        return model;
    }

    @JsonProperty("document")
    public ParseDocument getDocument() {
        return document;
    }

    @JsonProperty("output_format")
    public Optional<ParseOutputFormat> getOutputFormat() {
        return outputFormat;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ParseRequest && equalTo((ParseRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ParseRequest other) {
        return model.equals(other.model) && document.equals(other.document) && outputFormat.equals(other.outputFormat);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.model, this.document, this.outputFormat);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ModelStage builder() {
        return new Builder();
    }

    public interface ModelStage {
        /**
         * <p>The name of a compatible Cohere parse model.</p>
         */
        DocumentStage model(@NotNull String model);

        Builder from(ParseRequest other);
    }

    public interface DocumentStage {
        _FinalStage document(@NotNull ParseDocument document);
    }

    public interface _FinalStage {
        ParseRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage outputFormat(Optional<ParseOutputFormat> outputFormat);

        _FinalStage outputFormat(ParseOutputFormat outputFormat);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ModelStage, DocumentStage, _FinalStage {
        private String model;

        private ParseDocument document;

        private Optional<ParseOutputFormat> outputFormat = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ParseRequest other) {
            model(other.getModel());
            document(other.getDocument());
            outputFormat(other.getOutputFormat());
            return this;
        }

        /**
         * <p>The name of a compatible Cohere parse model.</p>
         * <p>The name of a compatible Cohere parse model.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("model")
        public DocumentStage model(@NotNull String model) {
            this.model = Objects.requireNonNull(model, "model must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("document")
        public _FinalStage document(@NotNull ParseDocument document) {
            this.document = Objects.requireNonNull(document, "document must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage outputFormat(ParseOutputFormat outputFormat) {
            this.outputFormat = Optional.ofNullable(outputFormat);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "output_format", nulls = Nulls.SKIP)
        public _FinalStage outputFormat(Optional<ParseOutputFormat> outputFormat) {
            this.outputFormat = outputFormat;
            return this;
        }

        @java.lang.Override
        public ParseRequest build() {
            return new ParseRequest(model, document, outputFormat, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
