/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.errors;

import com.cohere.api.core.CohereApiException;
import okhttp3.Response;

public final class ServiceUnavailableError extends CohereApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final Object body;

    public ServiceUnavailableError(Object body) {
        super("ServiceUnavailableError", 503, body);
        this.body = body;
    }

    public ServiceUnavailableError(Object body, Response rawResponse) {
        super("ServiceUnavailableError", 503, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public Object body() {
        return this.body;
    }
}
