/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.resources.audio.transcriptions;

import com.cohere.api.core.ClientOptions;
import com.cohere.api.core.RequestOptions;
import com.cohere.api.resources.audio.transcriptions.requests.TranscriptionsCreateRequest;
import com.cohere.api.resources.audio.transcriptions.types.AudioTranscriptionsCreateResponse;
import java.io.File;
import java.io.InputStream;
import java.util.concurrent.CompletableFuture;
import okhttp3.MediaType;

public class AsyncTranscriptionsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawTranscriptionsClient rawClient;

    public AsyncTranscriptionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawTranscriptionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawTranscriptionsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Transcribe an audio file.
     */
    public CompletableFuture<AudioTranscriptionsCreateResponse> create(File file, TranscriptionsCreateRequest request) {
        return this.rawClient.create(file, request).thenApply(response -> response.body());
    }

    /**
     * Transcribe an audio file.
     */
    public CompletableFuture<AudioTranscriptionsCreateResponse> create(
            File file, TranscriptionsCreateRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(file, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<AudioTranscriptionsCreateResponse> create(InputStream stream, String filename) {
        return this.rawClient.create(stream, filename).thenApply(response -> response.body());
    }

    public CompletableFuture<AudioTranscriptionsCreateResponse> create(
            InputStream stream, String filename, MediaType mediaType) {
        return this.rawClient.create(stream, filename, mediaType).thenApply(response -> response.body());
    }

    public CompletableFuture<AudioTranscriptionsCreateResponse> create(
            InputStream stream, String filename, RequestOptions requestOptions) {
        return this.rawClient.create(stream, filename, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<AudioTranscriptionsCreateResponse> create(
            InputStream stream, String filename, MediaType mediaType, RequestOptions requestOptions) {
        return this.rawClient
                .create(stream, filename, mediaType, requestOptions)
                .thenApply(response -> response.body());
    }
}
