/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.types;

import com.cohere.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.List;
import java.util.Objects;

@JsonDeserialize(using = AssistantMessageV2Content.Deserializer.class)
public final class AssistantMessageV2Content {
    private final Object value;

    private final int type;

    private AssistantMessageV2Content(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((String) this.value);
        } else if (this.type == 1) {
            return visitor.visit((List<AssistantMessageV2ContentItem>) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AssistantMessageV2Content && equalTo((AssistantMessageV2Content) other);
    }

    private boolean equalTo(AssistantMessageV2Content other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static AssistantMessageV2Content of(String value) {
        return new AssistantMessageV2Content(value, 0);
    }

    public static AssistantMessageV2Content of(List<AssistantMessageV2ContentItem> value) {
        return new AssistantMessageV2Content(value, 1);
    }

    public interface Visitor<T> {
        T visit(String value);

        T visit(List<AssistantMessageV2ContentItem> value);
    }

    static final class Deserializer extends StdDeserializer<AssistantMessageV2Content> {
        Deserializer() {
            super(AssistantMessageV2Content.class);
        }

        @java.lang.Override
        public AssistantMessageV2Content deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
            } catch (IllegalArgumentException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(
                        value, new TypeReference<List<AssistantMessageV2ContentItem>>() {}));
            } catch (IllegalArgumentException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
