/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum AuthTokenType {
    BEARER("bearer"),

    BASIC("basic"),

    NOSCHEME("noscheme");

    private final String value;

    AuthTokenType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
