/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.types;

import com.cohere.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ChatMessage.Builder.class)
public final class ChatMessage {
    private final String message;

    private final Optional<List<ToolCall>> toolCalls;

    private final Map<String, Object> additionalProperties;

    private ChatMessage(String message, Optional<List<ToolCall>> toolCalls, Map<String, Object> additionalProperties) {
        this.message = message;
        this.toolCalls = toolCalls;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Contents of the chat message.
     */
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    @JsonProperty("tool_calls")
    public Optional<List<ToolCall>> getToolCalls() {
        return toolCalls;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ChatMessage && equalTo((ChatMessage) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ChatMessage other) {
        return message.equals(other.message) && toolCalls.equals(other.toolCalls);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.message, this.toolCalls);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MessageStage builder() {
        return new Builder();
    }

    public interface MessageStage {
        /**
         * <p>Contents of the chat message.</p>
         */
        _FinalStage message(@NotNull String message);

        Builder from(ChatMessage other);
    }

    public interface _FinalStage {
        ChatMessage build();

        _FinalStage toolCalls(Optional<List<ToolCall>> toolCalls);

        _FinalStage toolCalls(List<ToolCall> toolCalls);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MessageStage, _FinalStage {
        private String message;

        private Optional<List<ToolCall>> toolCalls = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ChatMessage other) {
            message(other.getMessage());
            toolCalls(other.getToolCalls());
            return this;
        }

        /**
         * <p>Contents of the chat message.</p>
         * <p>Contents of the chat message.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("message")
        public _FinalStage message(@NotNull String message) {
            this.message = Objects.requireNonNull(message, "message must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage toolCalls(List<ToolCall> toolCalls) {
            this.toolCalls = Optional.ofNullable(toolCalls);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "tool_calls", nulls = Nulls.SKIP)
        public _FinalStage toolCalls(Optional<List<ToolCall>> toolCalls) {
            this.toolCalls = toolCalls;
            return this;
        }

        @java.lang.Override
        public ChatMessage build() {
            return new ChatMessage(message, toolCalls, additionalProperties);
        }
    }
}
