/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ChatStreamEndEventFinishReason {
    COMPLETE("COMPLETE"),

    ERROR_LIMIT("ERROR_LIMIT"),

    MAX_TOKENS("MAX_TOKENS"),

    ERROR("ERROR"),

    ERROR_TOXIC("ERROR_TOXIC");

    private final String value;

    ChatStreamEndEventFinishReason(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
