/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.types;

import com.cohere.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Citation.Builder.class)
public final class Citation {
    private final Optional<Integer> start;

    private final Optional<Integer> end;

    private final Optional<String> text;

    private final Optional<List<Source>> sources;

    private final Optional<Integer> contentIndex;

    private final Optional<CitationType> type;

    private final Map<String, Object> additionalProperties;

    private Citation(
            Optional<Integer> start,
            Optional<Integer> end,
            Optional<String> text,
            Optional<List<Source>> sources,
            Optional<Integer> contentIndex,
            Optional<CitationType> type,
            Map<String, Object> additionalProperties) {
        this.start = start;
        this.end = end;
        this.text = text;
        this.sources = sources;
        this.contentIndex = contentIndex;
        this.type = type;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Start index of the cited snippet in the original source text.
     */
    @JsonProperty("start")
    public Optional<Integer> getStart() {
        return start;
    }

    /**
     * @return End index of the cited snippet in the original source text.
     */
    @JsonProperty("end")
    public Optional<Integer> getEnd() {
        return end;
    }

    /**
     * @return Text snippet that is being cited.
     */
    @JsonProperty("text")
    public Optional<String> getText() {
        return text;
    }

    @JsonProperty("sources")
    public Optional<List<Source>> getSources() {
        return sources;
    }

    /**
     * @return Index of the content block in which this citation appears.
     */
    @JsonProperty("content_index")
    public Optional<Integer> getContentIndex() {
        return contentIndex;
    }

    @JsonProperty("type")
    public Optional<CitationType> getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Citation && equalTo((Citation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Citation other) {
        return start.equals(other.start)
                && end.equals(other.end)
                && text.equals(other.text)
                && sources.equals(other.sources)
                && contentIndex.equals(other.contentIndex)
                && type.equals(other.type);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.start, this.end, this.text, this.sources, this.contentIndex, this.type);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> start = Optional.empty();

        private Optional<Integer> end = Optional.empty();

        private Optional<String> text = Optional.empty();

        private Optional<List<Source>> sources = Optional.empty();

        private Optional<Integer> contentIndex = Optional.empty();

        private Optional<CitationType> type = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(Citation other) {
            start(other.getStart());
            end(other.getEnd());
            text(other.getText());
            sources(other.getSources());
            contentIndex(other.getContentIndex());
            type(other.getType());
            return this;
        }

        /**
         * <p>Start index of the cited snippet in the original source text.</p>
         */
        @JsonSetter(value = "start", nulls = Nulls.SKIP)
        public Builder start(Optional<Integer> start) {
            this.start = start;
            return this;
        }

        public Builder start(Integer start) {
            this.start = Optional.ofNullable(start);
            return this;
        }

        /**
         * <p>End index of the cited snippet in the original source text.</p>
         */
        @JsonSetter(value = "end", nulls = Nulls.SKIP)
        public Builder end(Optional<Integer> end) {
            this.end = end;
            return this;
        }

        public Builder end(Integer end) {
            this.end = Optional.ofNullable(end);
            return this;
        }

        /**
         * <p>Text snippet that is being cited.</p>
         */
        @JsonSetter(value = "text", nulls = Nulls.SKIP)
        public Builder text(Optional<String> text) {
            this.text = text;
            return this;
        }

        public Builder text(String text) {
            this.text = Optional.ofNullable(text);
            return this;
        }

        @JsonSetter(value = "sources", nulls = Nulls.SKIP)
        public Builder sources(Optional<List<Source>> sources) {
            this.sources = sources;
            return this;
        }

        public Builder sources(List<Source> sources) {
            this.sources = Optional.ofNullable(sources);
            return this;
        }

        /**
         * <p>Index of the content block in which this citation appears.</p>
         */
        @JsonSetter(value = "content_index", nulls = Nulls.SKIP)
        public Builder contentIndex(Optional<Integer> contentIndex) {
            this.contentIndex = contentIndex;
            return this;
        }

        public Builder contentIndex(Integer contentIndex) {
            this.contentIndex = Optional.ofNullable(contentIndex);
            return this;
        }

        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<CitationType> type) {
            this.type = type;
            return this;
        }

        public Builder type(CitationType type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        public Citation build() {
            return new Citation(start, end, text, sources, contentIndex, type, additionalProperties);
        }
    }
}
