/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum EmbedInputType {
    SEARCH_DOCUMENT("search_document"),

    SEARCH_QUERY("search_query"),

    CLASSIFICATION("classification"),

    CLUSTERING("clustering"),

    IMAGE("image");

    private final String value;

    EmbedInputType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
