/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum GenerateStreamRequestReturnLikelihoods {
    GENERATION("GENERATION"),

    ALL("ALL"),

    NONE("NONE");

    private final String value;

    GenerateStreamRequestReturnLikelihoods(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
