/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.types;

import com.cohere.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ParseTableContentBlock.Builder.class)
public final class ParseTableContentBlock {
    private final ParseTableBlock table;

    private final Map<String, Object> additionalProperties;

    private ParseTableContentBlock(ParseTableBlock table, Map<String, Object> additionalProperties) {
        this.table = table;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("table")
    public ParseTableBlock getTable() {
        return table;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ParseTableContentBlock && equalTo((ParseTableContentBlock) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ParseTableContentBlock other) {
        return table.equals(other.table);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.table);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TableStage builder() {
        return new Builder();
    }

    public interface TableStage {
        _FinalStage table(@NotNull ParseTableBlock table);

        Builder from(ParseTableContentBlock other);
    }

    public interface _FinalStage {
        ParseTableContentBlock build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TableStage, _FinalStage {
        private ParseTableBlock table;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ParseTableContentBlock other) {
            table(other.getTable());
            return this;
        }

        @java.lang.Override
        @JsonSetter("table")
        public _FinalStage table(@NotNull ParseTableBlock table) {
            this.table = Objects.requireNonNull(table, "table must not be null");
            return this;
        }

        @java.lang.Override
        public ParseTableContentBlock build() {
            return new ParseTableContentBlock(table, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
