/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SummarizeRequestLength {
    SHORT("short"),

    MEDIUM("medium"),

    LONG("long");

    private final String value;

    SummarizeRequestLength(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
