/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.types;

import com.cohere.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SystemMessageV2.Builder.class)
public final class SystemMessageV2 {
    private final SystemMessageV2Content content;

    private final Map<String, Object> additionalProperties;

    private SystemMessageV2(SystemMessageV2Content content, Map<String, Object> additionalProperties) {
        this.content = content;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("content")
    public SystemMessageV2Content getContent() {
        return content;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SystemMessageV2 && equalTo((SystemMessageV2) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SystemMessageV2 other) {
        return content.equals(other.content);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.content);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ContentStage builder() {
        return new Builder();
    }

    public interface ContentStage {
        _FinalStage content(@NotNull SystemMessageV2Content content);

        Builder from(SystemMessageV2 other);
    }

    public interface _FinalStage {
        SystemMessageV2 build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ContentStage, _FinalStage {
        private SystemMessageV2Content content;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SystemMessageV2 other) {
            content(other.getContent());
            return this;
        }

        @java.lang.Override
        @JsonSetter("content")
        public _FinalStage content(@NotNull SystemMessageV2Content content) {
            this.content = Objects.requireNonNull(content, "content must not be null");
            return this;
        }

        @java.lang.Override
        public SystemMessageV2 build() {
            return new SystemMessageV2(content, additionalProperties);
        }
    }
}
