/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.resources.batches.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BatchStatus {
    public static final BatchStatus BATCH_STATUS_QUEUED =
            new BatchStatus(Value.BATCH_STATUS_QUEUED, "BATCH_STATUS_QUEUED");

    public static final BatchStatus BATCH_STATUS_IN_PROGRESS =
            new BatchStatus(Value.BATCH_STATUS_IN_PROGRESS, "BATCH_STATUS_IN_PROGRESS");

    public static final BatchStatus BATCH_STATUS_UNSPECIFIED =
            new BatchStatus(Value.BATCH_STATUS_UNSPECIFIED, "BATCH_STATUS_UNSPECIFIED");

    public static final BatchStatus BATCH_STATUS_FAILED =
            new BatchStatus(Value.BATCH_STATUS_FAILED, "BATCH_STATUS_FAILED");

    public static final BatchStatus BATCH_STATUS_CANCELING =
            new BatchStatus(Value.BATCH_STATUS_CANCELING, "BATCH_STATUS_CANCELING");

    public static final BatchStatus BATCH_STATUS_CANCELED =
            new BatchStatus(Value.BATCH_STATUS_CANCELED, "BATCH_STATUS_CANCELED");

    public static final BatchStatus BATCH_STATUS_COMPLETED =
            new BatchStatus(Value.BATCH_STATUS_COMPLETED, "BATCH_STATUS_COMPLETED");

    private final Value value;

    private final String string;

    BatchStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof BatchStatus && this.string.equals(((BatchStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case BATCH_STATUS_QUEUED:
                return visitor.visitBatchStatusQueued();
            case BATCH_STATUS_IN_PROGRESS:
                return visitor.visitBatchStatusInProgress();
            case BATCH_STATUS_UNSPECIFIED:
                return visitor.visitBatchStatusUnspecified();
            case BATCH_STATUS_FAILED:
                return visitor.visitBatchStatusFailed();
            case BATCH_STATUS_CANCELING:
                return visitor.visitBatchStatusCanceling();
            case BATCH_STATUS_CANCELED:
                return visitor.visitBatchStatusCanceled();
            case BATCH_STATUS_COMPLETED:
                return visitor.visitBatchStatusCompleted();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BatchStatus valueOf(String value) {
        switch (value) {
            case "BATCH_STATUS_QUEUED":
                return BATCH_STATUS_QUEUED;
            case "BATCH_STATUS_IN_PROGRESS":
                return BATCH_STATUS_IN_PROGRESS;
            case "BATCH_STATUS_UNSPECIFIED":
                return BATCH_STATUS_UNSPECIFIED;
            case "BATCH_STATUS_FAILED":
                return BATCH_STATUS_FAILED;
            case "BATCH_STATUS_CANCELING":
                return BATCH_STATUS_CANCELING;
            case "BATCH_STATUS_CANCELED":
                return BATCH_STATUS_CANCELED;
            case "BATCH_STATUS_COMPLETED":
                return BATCH_STATUS_COMPLETED;
            default:
                return new BatchStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        BATCH_STATUS_UNSPECIFIED,

        BATCH_STATUS_QUEUED,

        BATCH_STATUS_IN_PROGRESS,

        BATCH_STATUS_CANCELING,

        BATCH_STATUS_COMPLETED,

        BATCH_STATUS_FAILED,

        BATCH_STATUS_CANCELED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitBatchStatusUnspecified();

        T visitBatchStatusQueued();

        T visitBatchStatusInProgress();

        T visitBatchStatusCanceling();

        T visitBatchStatusCompleted();

        T visitBatchStatusFailed();

        T visitBatchStatusCanceled();

        T visitUnknown(String unknownType);
    }
}
