/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api.resources.audio;

import com.cohere.api.core.ClientOptions;
import com.cohere.api.core.Suppliers;
import com.cohere.api.resources.audio.transcriptions.AsyncTranscriptionsClient;
import java.util.function.Supplier;

public class AsyncAudioClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncTranscriptionsClient> transcriptionsClient;

    public AsyncAudioClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.transcriptionsClient = Suppliers.memoize(() -> new AsyncTranscriptionsClient(clientOptions));
    }

    public AsyncTranscriptionsClient transcriptions() {
        return this.transcriptionsClient.get();
    }
}
