/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api;

import com.cohere.api.core.ClientOptions;
import com.cohere.api.core.Environment;

public final class CohereBuilder {
    private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

    private String token = null;

    private String clientName = null;

    private Environment environment = Environment.PRODUCTION;

    /**
     * Sets token
     */
    public CohereBuilder token(String token) {
        this.token = token;
        return this;
    }

    /**
     * Sets clientName
     */
    public CohereBuilder clientName(String clientName) {
        this.clientName = clientName;
        return this;
    }

    public CohereBuilder environment(Environment environment) {
        this.environment = environment;
        return this;
    }

    public CohereBuilder url(String url) {
        this.environment = Environment.custom(url);
        return this;
    }

    public Cohere build() {
        if (token == null) {
            throw new RuntimeException("Please provide token");
        }
        this.clientOptionsBuilder.addHeader("Authorization", "Bearer " + this.token);
        if (clientName == null) {
            throw new RuntimeException("Please provide clientName");
        }
        this.clientOptionsBuilder.addHeader("X-Client-Name", this.clientName);
        clientOptionsBuilder.environment(this.environment);
        return new Cohere(clientOptionsBuilder.build());
    }
}
