/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.cohere.api;

import com.cohere.api.core.ClientOptions;
import com.cohere.api.core.Environment;

public final class CohereBuilder {
    private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

    private Environment environment = Environment.PRODUCTION;

    public CohereBuilder token(String token) {
        this.clientOptionsBuilder.addHeader("Authorization", "Bearer " + token);
        return this;
    }

    public CohereBuilder clientName(String clientName) {
        this.clientOptionsBuilder.addHeader("X-Client-Name", clientName);
        return this;
    }

    public CohereBuilder environment(Environment environment) {
        this.environment = environment;
        return this;
    }

    public CohereBuilder url(String url) {
        this.environment = Environment.custom(url);
        return this;
    }

    public Cohere build() {
        clientOptionsBuilder.environment(this.environment);
        return new Cohere(clientOptionsBuilder.build());
    }
}
